# Generated by Django 4.2.4 on 2023-12-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_level_delete_levels_pereval_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='data',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
